package com.rdevansh.quotesforthebest

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class QuotesOpenHelper(context: Context):SQLiteOpenHelper(context,null, null, 1)
{
    override fun onCreate(db: SQLiteDatabase?) {
        // Code to create tables and insert quote categories and quotes
        db!!.execSQL("Create Table quote_categories("+
                "_id INTEGER PRIMARY KEY," +
                "image_resource_id TEXT," +
                "name TEXT"+
                ")")

        insertQuoteCategory(db, 1, R.drawable.alone, "Alone")
        insertQuoteCategory(db, 2, R.drawable.birthday, "Birthday")
        insertQuoteCategory(db, 3, R.drawable.childhood, "Childhood")
        insertQuoteCategory(db, 4, R.drawable.creativity, "Creativity")
        insertQuoteCategory(db, 5, R.drawable.happy, "Happy")
        insertQuoteCategory(db, 6, R.drawable.inspirational, "Inspirational")
        insertQuoteCategory(db, 7, R.drawable.love, "Love")
        insertQuoteCategory(db, 8, R.drawable.marriage, "Marriage")
        insertQuoteCategory(db, 9, R.drawable.motivational, "Motivational")
        insertQuoteCategory(db, 10, R.drawable.nature, "Nature")
        insertQuoteCategory(db, 11, R.drawable.romantic, "Romantic")
        insertQuoteCategory(db, 12, R.drawable.sad, "Sad")
        insertQuoteCategory(db, 13, R.drawable.thoughtful, "Thoughtful")


        // Quotes Table

        db!!.execSQL("CREATE TABLE quotes("+
        "quote TEXT,"+
        "category_id INTEGER)")

        insertQuote(db, "Please don’t try to fix me. Please understand that I just get sad sometimes. Sometimes I shut the world out and when I feel better I’ll let it back in.", 1)
        insertQuote(db, "Sometimes, you find yourself in the middle of nowhere, and sometimes, in the middle of nowhere, you find yourself.", 1)
        insertQuote(db, "I am me, nothing more, nothing less, and that is enough.", 1)
        insertQuote(db, "Nothing can bring you peace but yourself.", 1)
        insertQuote(db, "A healthy relationship will never require you to sacrifice your friends, your dreams, or your dignity.", 1)
        insertQuote(db, "Everything has changed and yet, I am more me than I've ever been.", 1)
        insertQuote(db,  "It is okay to live a life others do not understand.", 1)
        insertQuote(db, "I’m learning a lot about myself being alone, and doing what I’m doing.", 1)
        insertQuote(db, "Loneliness expresses the pain of being alone and solitude expresses the glory of being alone.", 1)
        insertQuote(db, "I finally faced the fact that it isn’t a crime not having friends. Being alone means you have fewer problems.", 1)
        insertQuote(db, "Don’t go away. I don’t want to be alone. I can’t stand being alone.", 1)
        insertQuote(db, " I don’t know what else to do when I’m alone. I always think of you.", 1)
        insertQuote(db, "Sometimes life is too hard to be alone, and sometimes life is too good to be alone.", 1)
        insertQuote(db, "I enjoy being alone, my soul is at peace in the silence.", 1)
        insertQuote(db, "Be along. Get inside your mind. Figure things out. Grow.", 1)
        insertQuote(db, "The person who tries to keep everyone happy often ends up feeling the loneliest.", 1)
        insertQuote(db, "Be willing to walk alone. Many who started with you wont finish with you.", 1)
        insertQuote(db, "Funny thing is when you start feeling happy alone, everyone else wants to be with you", 1)
        insertQuote(db, "I don’t need anybody telling me how to fix my own damn life. I can do it alone.", 1)
        insertQuote(db, "Freedom of being alone is intoxicating.", 1)
        insertQuote(db, "Being alone has a power that very few can handle.", 1)
        insertQuote(db, "I like to be alone, but I being lonely", 1)
        insertQuote(db, "It’s better to have nobody than to have someone who is half there or doesn’t want to be there.", 1)
        insertQuote(db, "Standing alone doesn’t mean I’m alone. It means I am strong enough the handle things all by myself.", 1)
        insertQuote(db, "It takes nothing to join the crowd. It takes everything to stand alone.", 1)
        insertQuote(db, "It’s better to be alone than to be with those who hinder your progress.", 1)
        insertQuote(db, "You never really stop loving someone. You just learn to try to live without them.", 1)
        insertQuote(db, "Love when you’re ready, not when you’re lonely.", 1)
        insertQuote(db, "You will be happy, said life, but first I must make you strong.", 1)

        insertQuote(db, "Count your life by smiles, not tears. Count your age by friends, not years. Happy birthday!", 2)
        insertQuote(db, "A wish for you on your birthday, whatever you ask may you receive, whatever you seek may you find, whatever you wish may it be fulfilled on your birthday and always. Happy birthday!", 2)
        insertQuote(db, " Another adventure filled year awaits you. Welcome it by celebrating your birthday with pomp and splendor. Wishing you a very happy and fun-filled birthday!", 2)
        insertQuote(db, "May the joy that you have spread in the past come back to you on this day. Wishing you a very happy birthday!", 2)
        insertQuote(db, "Count not the candles, see the lights they give. Count not the years, but the life you live. Wishing you a wonderful time ahead. Happy birthday.", 2)
        insertQuote(db, "Forget about the past, you can’t change it. Forget about the future, you can’t predict it. And forget about the present, I didn’t get you one. Happy birthday!", 2)
        insertQuote(db, "You’re older today than yesterday but younger than tomorrow, happy birthday!", 2)
        insertQuote(db, "Happy birthday to one of the few people whose birthday I can remember without a Facebook reminder.", 2)
        insertQuote(db, "As you get older three things happen. The first is your memory goes, and I can’t remember the other two. Happy birthday!", 2)
        insertQuote(db, "Sending you smiles for every moment of your special day…Have a wonderful time and a very happy birthday!", 2)
        insertQuote(db, "Your birthday is the first day of another 365-day journey. Be the shining thread in the beautiful tapestry of the world to make this year the best ever. Enjoy the ride.", 2)
        insertQuote(db, "Happy birthday to someone who is forever young!", 2)
        insertQuote(db, "Wishing you a day filled with happiness and a year filled with joy.", 2)
        insertQuote(db, "Sending your way a bouquet of happiness…To wish you a very happy birthday!", 2)
        insertQuote(db, "A birthday means that you are a year older, but a birthday party means you get to act 10 years younger. Enjoy the party!", 2)
        insertQuote(db, "Happy moments. Happy thoughts. Happy dreams. Happy feelings. Happy birthday.", 2)
        insertQuote(db, "Celebrating your birthday is just like celebrating the birthday of a friend I didn’t get to choose.", 2)
        insertQuote(db, "Dad, your birthday gift is another year of not having to pay for my wedding.", 2)
        insertQuote(db, "On your birthday, look to the future and forget your past- the best is still to come. Happy birthday, friend.", 2)
        insertQuote(db, "May this special day bring you endless joy and tons of precious memories!", 2)
        insertQuote(db, "I don’t have words to describe what I feel for you. Meeting you is the best thing that ever happened in my life. Happy Birthday!", 2)
        insertQuote(db, "I wish you a day filled with great fun and a year filled with true happiness!", 2)
        insertQuote(db, "May this day be so happy that smile never fades away from your face.", 2)
        insertQuote(db, "May your birthday mark the beginning of a wonderful period of time in your life!", 2)
        insertQuote(db, "A birth-date is a reminder to celebrate the life as well as to update the life.", 2)
        insertQuote(db, "If I could save time in a bottle, the first thing that I'd like to do is to save every day.", 2)


        insertQuote(db, "Childhood is the kingdom where nobody dies.", 3)
        insertQuote(db, "I clearly remember that day, when we were still so young, when everything was still alright.", 3)
        insertQuote(db, "Sometimes, I wish I am a child again so I can be whoever I want to be in the future, I wish.", 3)
        insertQuote(db, "That sad moment when you realize your childhood is over.", 3)
        insertQuote(db, "Your adulthood is a by-product of your teenage-hood, which is a complicated version of childhood.", 3)
        insertQuote(db, "I spent my whole childhood wishing I were older and now I’m spending my adulthood wishing I were younger.", 3)
        insertQuote(db, "There is a garden in every childhood, an enchanted place where colors are brighter, the air softer, and the morning more fragrant than ever again.", 3)
        insertQuote(db, "Childhood is the fiery furnace in which we are melted down to essentials and that essential shaped for good. c", 3)
        insertQuote(db, "Did you know that childhood is the only time in our lives when insanity is not only permitted to us, but expected ?", 3)
        insertQuote(db, "My childhood is a part of my story, and it’s why I’m who I am today and why my career is what it is.", 3)

        insertQuote(db, "Creativity doesn't wait for that perfect moment. It fashions its own perfect moments out of ordinary ones.", 4)
        insertQuote(db, "The desire to create is one of the deepest yearnings of the human soul.", 4)
        insertQuote(db, "Everything you can imagine is real.", 4)
        insertQuote(db, "You can't use up creativity. The more you use the more you have.", 4)
        insertQuote(db, "Creativity is intelligence having fun.", 4)
        insertQuote(db, "To practice any art, no matter how well or badly, is a way to make your soul grow. So do it.", 4)
        insertQuote(db, "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.", 4)
        insertQuote(db, "The chief enemy of creativity is \"good\" sense.", 4)
        insertQuote(db, "Creativity involves breaking out of expected patterns in order to look at things in a different way.", 4)
        insertQuote(db, "Start where you are. Use what you have. Do what you can.", 4)
        insertQuote(db, "ou never have to change anything you got up in the middle of the night to write.", 4)

        insertQuote(db, "I know I am not ALONE....", 5)
        insertQuote(db, "Happiness is a direction, not a place.", 5)
        insertQuote(db, "Learn to value yourself, which means: fight for your happiness.", 5)
        insertQuote(db, "The true secret of happiness lies in the taking a genuine interest in all the details of daily life.", 5)
        insertQuote(db, "The greatest happiness you can have is knowing that you do not necessarily require happiness.", 5)
        insertQuote(db, "As people spin faster and faster in the pursuit of merely personal happiness, they become exhausted in the futile effort of chasing themselves.", 5)
        insertQuote(db, "Happiness is not an ideal of reason, but of imagination.", 5)
        insertQuote(db, "A great obstacle to happiness is to expect too much happiness.", 5)
        insertQuote(db, "There is some kind of a sweet innocence in being human—in not having to be just happy or just sad—in the nature of being able to be both broken and whole, at the same time.", 5)
        insertQuote(db, "The secret of happiness is freedom, the secret of freedom is courage.", 5)
        insertQuote(db, "The only way to find true happiness is to risk being completely cut open.", 5)
        insertQuote(db, "Happiness is not something ready made. It comes from your own actions.", 5)
        insertQuote(db, "Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude.", 5)
        insertQuote(db, "I think the key to life is just being a happy person, and happiness will bring you success.", 5)
        insertQuote(db, "Happiness grows at our own firesides, and is not to be picked in strangers’ gardens.", 5)
        insertQuote(db, "Learn to enjoy every minute of your life. Be happy now. Don’t wait for something outside of yourself to make you happy in the future. Think how really precious is the time you have to spend, whether it’s at work or with your family. Every minute should be enjoyed and savored.", 5)
        insertQuote(db, "The search for happiness is one of the chief sources of unhappiness.", 5)

        insertQuote(db, "Your limitation—it’s only your imagination.", 6)
        insertQuote(db, "Push yourself, because no one else is going to do it for you.", 6)
        insertQuote(db, "Sometimes later becomes never. Do it now.", 6)
        insertQuote(db, "Great things never come from comfort zones.", 6)
        insertQuote(db, "Dream it. Wish it. Do it.", 6)
        insertQuote(db, "Success doesn’t just find you. You have to go out and get it.", 6)
        insertQuote(db, "The harder you work for something, the greater you’ll feel when you achieve it.", 6)
        insertQuote(db, "Dream bigger. Do bigger.", 6)
        insertQuote(db, "Don’t stop when you’re tired. Stop when you’re done.", 6)
        insertQuote(db, "Wake up with determination. Go to bed with satisfaction.", 6)
        insertQuote(db, "Do something today that your future self will thank you for.", 6)
        insertQuote(db, "Little things make big days.", 6)
        insertQuote(db, "It’s going to be hard, but hard does not mean impossible.", 6)
        insertQuote(db, "Don’t wait for opportunity. Create it.", 6)
        insertQuote(db, "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", 6)
        insertQuote(db, "The key to success is to focus on goals, not obstacles.\n", 6)
        insertQuote(db, "Dream it. Believe it. Build it.", 6)

        insertQuote(db, "The best and the worst thing about love is that it cannot be expressed in words.", 7)
        insertQuote(db, "I am happiest when I’m right next to you.", 7)
        insertQuote(db, "The water shines only by the sun. And it is you who are my sun.", 7)
        insertQuote(db, "My night has become a sunny dawn because of you.", 7)
        insertQuote(db, "I swear I couldn’t love you more than I do right now, and yet I know I will tomorrow.", 7)
        insertQuote(db, "The best thing to hold onto in life is each other.", 7)
        insertQuote(db, "I love you” begins by I, but it ends up by you.", 7)
        insertQuote(db, "You may hold my hand for a while, but you hold my heart forever.", 7)
        insertQuote(db, "There is a madness in loving you, a lack of reason that makes it feel so flawless.", 7)
        insertQuote(db, "I know I am in love with you because my reality is finally better than my dreams.", 7)
        insertQuote(db, "You are the last thought in my mind before I drift off to sleep and the first thought when I wake up each morning.", 7)
        insertQuote(db, "I need you like a heart needs a beat.", 7)
        insertQuote(db, "Your love is all I need to feel complete.", 7)
        insertQuote(db, "I will love you until the stars go out, and the tides no longer turn.", 7)
        insertQuote(db, "Come live in my heart and pay no rent.", 7)
        insertQuote(db, "Every time I see you, I fall in love all over again.", 7)
        insertQuote(db, "You are my song. You are my song of love.", 7)
        insertQuote(db, "If I know what love is, it is because of you.", 7)
        insertQuote(db, "To lose balance sometimes for love is part of living a balanced life.", 7)
        insertQuote(db, "Let us Flip the coin and see. Head, I am yours. Tail, you are mine. So, we won’t lose.", 7)
        insertQuote(db, "There are only two times that I want to be with you. Now and Forever.", 7)
        insertQuote(db, "Where there is Love, There is Life.", 7)
        insertQuote(db, "There is only happiness in life, to love and to be loved.", 7)
        insertQuote(db, "Without his love I can do nothing, with his love, there is nothing I cannot do.", 7)
        insertQuote(db, "Nobody has the ability to make me as weightless and carefree as you can.", 7)

        insertQuote(db, "Marriage lets you annoy one special person for the rest of your life.", 8)
        insertQuote(db, "Marriage is not just spiritual communion, it is also remembering to take out the trash.", 8)
        insertQuote(db, "When a man opens a car door for his wife, it’s either a new car or a new wife.", 8)
        insertQuote(db, "An archaeologist is the best husband a woman can have. The older she gets, the more interested he is in her.", 8)
        insertQuote(db, "The great marriages are partnerships. It can’t be a great marriage without being a partnership.", 8)
        insertQuote(db, "My husband has made me laugh. Wiped my tears. Hugged me tight. Watched me succeed. Seen me fail. Kept me strong. My husband is a promise that I will have a friend forever.", 8)
        insertQuote(db, "In terms of my marriage, you know, falling in love with my husband was by far the best thing that’s ever happened to me.", 8)
        insertQuote(db, "A husband and wife may disagree on many things but they must absolutely agree on this: to never, ever give up.", 8)
        insertQuote(db, "A successful marriage requires falling in love many times, always with the same person.", 8)
        insertQuote(db, "Never marry the one you can live with, marry the one you cannot live without.", 8)
        insertQuote(db, "Marriage is not about age; it’s about finding the right person.", 8)
        insertQuote(db, "True love stands by each other’s side on good days and stands closer on bad days.", 8)
        insertQuote(db, "A great marriage is not when the ‘perfect couple’ comes together. It is when an imperfect couple learns to enjoy their differences.", 8)
        insertQuote(db, "Love is not weakness. It is strong. Only the sacrament of marriage can contain it.", 8)
        insertQuote(db, "Marriage is not a noun; it’s a verb. It isn’t something you get. It’s something you do. It’s the way you love your partner every day.", 8)
        insertQuote(db, "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", 8)
        insertQuote(db, "Don’t ever stop dating your wife and don’t ever stop flirting with your husband.", 8)
        insertQuote(db, "To love is nothing. To be loved is something. But to be loved by the person you love is everything.", 8)
        insertQuote(db, "May this marriage be full of laughter, our every day in paradise.", 8)
        insertQuote(db, "Marriage, ultimately, is the practice of becoming passionate friends.", 8)
        insertQuote(db, "Happy is the man who finds a true friend, and far happier is he who finds that true friend in his wife.", 8)
        insertQuote(db, "Marriage is the most natural state of man, and the state in which you will find solid happiness.", 8)
        insertQuote(db, "", 8)

        insertQuote(db, "The secret of getting ahead is getting started.", 9)
        insertQuote(db, "All our dreams can come true, if we have the courage to pursue them.", 9)
        insertQuote(db, "The best time to plant a tree was 20 years ago. The second best time is now.", 9)
        insertQuote(db, "It’s hard to beat a person who never gives up.", 9)
        insertQuote(db, "If people are doubting how far you can go, go so far that you can’t hear them anymore.", 9)
        insertQuote(db, "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", 9)
        insertQuote(db, "Everything you can imagine is real.", 9)
        insertQuote(db, "Do one thing every day that scares you.", 9)
        insertQuote(db, "It’s no use going back to yesterday, because you were a different person then.", 9)
        insertQuote(db, "Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.", 9)
        insertQuote(db, "The same boiling water that softens the potato hardens the egg. It’s what you’re made of. Not the circumstances.", 9)
        insertQuote(db, "You can either experience the pain of discipline or the pain of regret. The choice is yours.", 9)
        insertQuote(db, "Impossible is just an opinion.", 9)
        insertQuote(db, "Magic is believing in yourself. If you can make that happen, you can make anything happen.", 9)
        insertQuote(db, "If something is important enough, even if the odds are stacked against you, you should still do it.", 9)
        insertQuote(db, "People who wonder if the glass is half empty or full miss the point. The glass is refillable.", 9)
        insertQuote(db, "If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles.", 9)
        insertQuote(db, "Keep your eyes on the stars, and your feet on the ground.", 9)
        insertQuote(db, "If opportunity doesn’t knock, build a door.", 9)
        insertQuote(db, "Hard work beats talent when talent doesn’t work hard.", 9)
        insertQuote(db, "The only difference between ordinary and extraordinary is that little extra.", 9)
        insertQuote(db, "Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be.", 9)
        insertQuote(db, "Work hard, be kind, and amazing things will happen.", 9)
        insertQuote(db, "If you cannot do great things, do small things in a great way.", 9)
        insertQuote(db, "Sometimes when you’re in a dark place you think you’ve been buried but you’ve actually been planted.", 9)
        insertQuote(db, "Don’t limit your challenges. Challenge your limits.", 9)
        insertQuote(db, "Good. Better. Best. Never let it rest. ‘Til your good is better and your better is best.", 9)
        insertQuote(db, "Start where you are. Use what you have. Do what you can.", 9)
        insertQuote(db, "Go the extra mile. It’s never crowded there.", 9)
        insertQuote(db, "H.O.P.E. = Hold On. Pain Ends.", 9)

        insertQuote(db, "In every walk in with Nature, one receives far more than he seeks...", 10)
        insertQuote(db, "By discovering nature, You discover yourself...", 10)
        insertQuote(db, "Going to the mountains is going home ;)", 10)
        insertQuote(db, "We don't inherit the earth from our ancestors, We borrow it form our children...", 10)
        insertQuote(db, "I took a walk in the nature and came out taller than the trees", 10)
        insertQuote(db, "Nature always wears the colours of the spirit", 10)
        insertQuote(db, "Your deepest roots are in nature.  No matter who you are, where you live, or what kind of life you lead, you remain irrevocably linked with the rest of creation. ", 10)
        insertQuote(db, "Look deep into nature, and then you will understand everything better.", 10)
        insertQuote(db, "Over every mountain there is a path, although it may not be seen from the valley.", 10)
        insertQuote(db, "God is the friend of silence. See how nature – trees, flowers, grass- grows in silence; see the stars, the moon and the sun, how they move in silence… We need silence to be able to touch souls.", 10)
        insertQuote(db, "Just living is not enough… one must have sunshine, freedom, and a little flower.", 10)
        insertQuote(db, "Every flower is a soul blossoming in nature.", 10)
        insertQuote(db, "Green is the prime color of the world, and that from which its loveliness arises.", 10)
        insertQuote(db, "The sea, once it casts its spell, holds one in its net of wonder forever.", 10)
        insertQuote(db, "Knowing trees, I understand the meaning of patience. Knowing grass, I can appreciate persistence.", 10)
        insertQuote(db, "There are always flowers for those who want to see them.Sunset is still my favorite color, and rainbow is second.", 10)
        insertQuote(db, "There are always flowers for those who want to see them.", 10)
        insertQuote(db, "Colors are the smiles of nature.", 10)
        insertQuote(db, "Adopt the pace of nature: her secret is patience.", 10)
        insertQuote(db, "If I were a tree, I would have no reason to love a human.", 10)
        insertQuote(db, "Nature is not a place to visit. It is home.", 10)

        insertQuote(db, "True love is putting someone else before yourself.", 11)
        insertQuote(db, "I fell in love the way you fall asleep: slowly, and then all at once.", 11)
        insertQuote(db, "Take my hand, take my whole life too. For I can’t help falling in love with you.", 11)
        insertQuote(db, "The heart has its reasons which reason knows not.", 11)
        insertQuote(db, "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", 11)
        insertQuote(db, "Every heart sings a song, incomplete, until another heart whispers back. Those who wish to sing always find a song.", 11)
        insertQuote(db, "A great marriage is not when the ‘perfect couple’ comes together. It is when an imperfect couple learns to enjoy their differences.", 11)
        insertQuote(db, "I don’t want to be your favorite or your best. I want to be your only and forget the rest.", 11)
        insertQuote(db, "I am absolutely, definitely, positively, unquestionably, beyond any doubt, in love with you.", 11)
        insertQuote(db, "No matter what has happened. No matter what you’ve done. No matter what you will do. I will always love you. I swear it.", 11)
        insertQuote(db, "You’re my favorite way to pass the time. But time stands still when you’re on my mind.", 11)
        insertQuote(db, "You know it’s true. Everything I do, I do it for you.", 11)
        insertQuote(db, "The more I see you, the more I want you. Somehow this feeling just grows and grows. With every sigh, I become more mad about you.", 11)
        insertQuote(db, "I won’t hesitate. No more, no more. It cannot wait, I’m yours.", 11)
        insertQuote(db, "When you say you love me, for a moment, there’s no one else alive.", 11)
        insertQuote(db, "Maybe it is our imperfections which make us so perfect for one another", 11)
        insertQuote(db, "Sometimes you do find what you’re looking for closer than you think.", 11)
        insertQuote(db, "I am my beloved’s and my beloved is mine.", 11)
        insertQuote(db, "Distance means so little when someone means so much.", 11)
        insertQuote(db, "True love cannot be contained by borders; it penetrates miles, zip codes, and state lines.", 11)
        insertQuote(db, "Love is that condition in which the happiness of another person is essential to your own.", 11)
        insertQuote(db, "I am who I am because of you. You are every reason, every hope, and every dream I’ve ever had.", 11)
        insertQuote(db, "Sometimes all you need is a hug from the right person and all your stress will melt away.", 11)

        insertQuote(db, "A million words would not bring you back, I know because I tried, neither would a million tears, I know because I cried.", 12)
        insertQuote(db, "Things change. And friends leave. Life doesn't stop for anybody.", 12)
        insertQuote(db, "Breathing is hard. When you cry so much, it makes you realize that breathing is hard.", 12)
        insertQuote(db, "You cannot protect yourself from sadness without protecting yourself from happiness.", 12)
        insertQuote(db, "Tears come from the heart and not from the brain.", 12)
        insertQuote(db, "To have felt too much is to end in feeling nothing.", 12)
        insertQuote(db, "People keep telling me that life goes on, but to me that’s the saddest part", 12)
        insertQuote(db, "It's sad when someone you know becomes someone you knew.", 12)
        insertQuote(db, "It will never rain roses: when we want to have more roses, we must plant more roses.", 12)
        insertQuote(db, "Life's under no obligation to give us what we expect.", 12)
        insertQuote(db, "Sometimes you've got to be able to listen to yourself and be okay with no one else understanding.", 12)
        insertQuote(db, "One thing you can't hide — is when you're crippled inside.", 12)
        insertQuote(db, "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", 12)
        insertQuote(db, "Our greatest joy and our greatest pain come in our relationships with others.", 12)
        insertQuote(db, "It is sad not to love, but it is much sadder not to be able to love.", 12)
        insertQuote(db, "What brings us to tears, will lead us to grace. Our pain is never wasted.", 12)
        insertQuote(db, "Life is made of so many partings welded together.", 12)
        insertQuote(db, "When you’re happy you enjoy the music, but when you’re sad you understand the lyrics.", 12)
        insertQuote(db, "Sometimes you laugh because you’ve got no more room for crying.", 12)
        insertQuote(db, "I learned how to be happy because I know what unhappiness felt like.", 12)
        insertQuote(db, "The good life is not one immune to sadness but one in which suffering contributes to our development.", 12)
        insertQuote(db, "It’s sad when someone you know becomes someone you knew.", 12)
        insertQuote(db, "Ninety-nine percent of your problems are created by you because you take life seriously.", 12)
        insertQuote(db, "Nothing changes if nothing changes.", 12)
        insertQuote(db, "Don’t grieve. Anything you lose comes round in another form.", 12)
        insertQuote(db, "Don’t desire happiness because it creates only unhappiness and nothing else.", 12)
        insertQuote(db, "Friendship = vulnerability * time. If loneliness is epidemic, this seems like an important part of the fix.", 12)
        insertQuote(db, "You don’t need water to feel like you’re drowning, do you?", 12)
        insertQuote(db, "Love is not a victory march. It’s a cold and it’s a broken hallelujah.", 12)
        insertQuote(db, "There are two medicines for all ills: time and silence.", 12)
        insertQuote(db, "Blaming other people for things that are going wrong guarantees your continued misery.", 12)
        insertQuote(db, "The opposite of love is indifference.", 12)
        insertQuote(db, "Tears are words the heart can’t express.", 12)
        insertQuote(db, "I always like walking in the rain, so no one can see me crying.", 12)
        insertQuote(db, "You said you’d always be there for me, but you’re not.", 12)
        insertQuote(db, "One thing you can’t hide — is when you’re crippled inside.", 12)
        insertQuote(db, "The funniest people are the saddest ones.", 12)
        insertQuote(db, "The sadness will last forever.", 12)
        insertQuote(db, "People cry, not because they’re weak. It’s because they’ve been strong for too long.", 12)
        insertQuote(db, "Some people care too much. I think it’s called love.", 12)
        insertQuote(db, "I am just another dot in the world.", 12)

        insertQuote(db, "Humility is not thinking less of yourself, it’s thinking of yourself less.", 13)
        insertQuote(db, "Experience is not what happens to you; it’s what you do with what happens to you", 13)
        insertQuote(db, "Better to light a candle than to curse the darkness.", 13)
        insertQuote(db, "We cannot solve our problems with the same thinking we used when we created them", 13)
        insertQuote(db, "The lonely become either thoughtful or empty", 13)
        insertQuote(db, "The purest and most thoughtful minds are those which love colour the most", 13)
        insertQuote(db, "Life is too important to take seriously", 13)
        insertQuote(db, "Without order nothing can exist—without chaos nothing can evolve.", 13)
        insertQuote(db, "Nowadays people know the price of everything and the value of nothing.", 13)
        insertQuote(db, "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love", 13)
        insertQuote(db, "No one has ever become poor by giving", 13)
        insertQuote(db, "It’s not what you look at that matters, it’s what you see.", 13)
        insertQuote(db, "Believe that life is worth living and your belief will help create the fact.", 13)
        insertQuote(db, "Just living is not enough. One must have sunshine, freedom, and a little flower.", 13)
        insertQuote(db, "A man who dares to waste one hour of time has not discovered the value of life", 13)
        insertQuote(db, "Dream as if you’ll live forever, live as if you’ll die today.", 13)
        insertQuote(db, "Life is like a coin. You can spend it any way you wish, but you only spend it once.", 13)
        insertQuote(db, "In three words I can sum up everything I’ve learned about life: it goes on.", 13)
        insertQuote(db, "Life’s not always fair. Sometimes you can get a splinter even sliding down a rainbow", 13)
        insertQuote(db, "Nobody can go back and start a new beginning, but anyone can start today and make a new ending", 13)
        insertQuote(db, "The magic of first love is our ignorance that it can never end.", 13)
        insertQuote(db, "Love is much like a wild rose, beautiful and calm, but willing to draw blood in its defense.", 13)
        insertQuote(db, "When love is not madness, it is not love.", 13)
        insertQuote(db, "The language of friendship is not words but meanings.", 13)
        insertQuote(db, "A real leader faces the music, even when he doesn’t like the tune.", 13)
        insertQuote(db, "Without order nothing can exist—without chaos nothing can evolve.", 13)
        insertQuote(db, "It’s not what you look at that matters, it’s what you see.", 13)
        insertQuote(db, "Keep your face always toward the sunshine—and shadows will fall behind you.", 13)
        insertQuote(db, "Never underestimate the power of thought; it is the greatest path to discovery.", 13)
        insertQuote(db, "If there were one word that could act as a standard of conduct for one's entire life, perhaps it would be thoughtfulness. ", 13)
        insertQuote(db, "Stop the habit of wishful thinking and start the habit of thoughtful wishes. ", 13)
        insertQuote(db, "Meeting important emotional needs creates the feeling of love, but thoughtfulness keeps it alive.   ", 13)
        insertQuote(db, "The two most powerful things in existence: a kind word and a thoughtful gesture.   ", 13)
        insertQuote(db, "Be purposeful and thoughtful in the choices you make when the options are neatly infinite.     ", 13)
        insertQuote(db, "The purest and most thoughtful minds are those which love colour the most.", 13)
        insertQuote(db, "Be thoughtful of others and you will not be shy, for they are incompatible addictions. ", 13)

    }

    fun insertQuote(db: SQLiteDatabase?, quote:String, categoryId:Int)
    {
        val contentValues = ContentValues()
        contentValues.put("quote", quote)
        contentValues.put("category_id", categoryId)

        db!!.insert("quotes", null, contentValues)
    }

    fun insertQuoteCategory(db:SQLiteDatabase?, id:Int, resourceId:Int, name:String)
    {
        val contentValues = ContentValues()
        contentValues.put("_id", id)
        contentValues.put("image_resource_id", resourceId)
        contentValues.put("name", name)

        db!!.insert("quote_categories", null, contentValues)
    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        TODO("Not yet implemented")
    }

}